# Generated by Django 5.1.7 on 2025-04-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_assessment_max_score_assessment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
